const fileUploaderConfig = {
    allowMultiple: false,
    maxFiles: 1,
    checkValidity: true,
    allowFilePoster: true,
    allowFileSizeValidation: true,
    maxFileSize: '1MB',
    labelMaxFileSizeExceeded: 'حجم فایل زیاد است',
    labelMaxFileSize: 'حداکثر حجم مجاز: {filesize}',
    filePosterMinHeight: 100,
    filePosterMaxHeight: 200,
    allowImagePreview: true,
    imagePreviewMaxHeight: 200,
    allowImageValidateSize: true,
    imageValidateSizeLabelFormatError: 'نوع عکس مجاز نیست',
    imageValidateSizeLabelImageSizeTooSmall: 'عکس بسیار کوچک است',
    imageValidateSizeLabelImageSizeTooBig: 'عکس بسیار بزرگ است',
    imageValidateSizeLabelExpectedMinSize: 'حداقل سایز عکس: {minWidth} × {minHeight}',
    imageValidateSizeLabelExpectedMaxSize: 'حداکثر سایز عکس: {maxWidth} × {maxHeight}',
    allowFileTypeValidation: true,
    acceptedFileTypes: ['image/png', 'image/jpg', 'image/jpeg'],
    labelFileTypeNotAllowed: 'فایل انتخابی مجاز نیست',
    server: {
        url: 'http://185.211.56.9:5000',
        process: '/Upload/Filepond',
        revert: {
            url: '/FilepondRevert',
            method: 'POST',
        },
    },
    labelIdle: 'آپلود تصویر پروفایل',
    labelInvalidField: 'فایل معنبر نیست',
    labelFileProcessing: 'درحال بارگذاری',
    labelFileProcessingError: 'خطا در بارگذاری',
    labelFileLoading: 'درحال بارگیری',
    labelFileLoadError: 'خطا در بارگیری',
    labelFileProcessingComplete: 'بارگذاری موفق',
    labelFileProcessingAborted: 'لغو بارگذاری',
    labelFileProcessingRevertError: 'خطا در بازگشتن',
    labelFileRemoveError: 'خطا در حذف',
    labelTapToCancel: 'لغو',
    labelTapToRetry: 'تلاش مجدد',
    labelTapToUndo: 'بازگردانی',
    labelButtonRemoveItem: 'حذف',
    labelButtonRetryItemLoad: 'تلاش مجدد',
    labelButtonAbortItemProcessing: 'لغو',
    labelButtonUndoItemProcessing: 'بازنشانی',
    labelButtonRetryItemProcessing: 'تلاش مجدد',
    labelButtonProcessItem: 'بارگذاری',
};

export default fileUploaderConfig;